version: '3.8'

services:
  rupaya-node:
    build: 
      context: .
      dockerfile: Dockerfile
    networks:
      - docker-compose_default
    ports:
      - "30303:30303"
      - "30303:30303/udp"
    volumes:
      - chaindata:/root/.ethereum
      - ./genesis.json:/root/genesis.json
    environment:
      - NETWORK_ID
      - SYNCMODE
      - GCMODE
      - HTTP_API
      - WS_API
      - BOOTNODES
      - VERBOSITY
      - IMPORT_PRIVATE_KEY
      - HTTP_RATELIMIT
      - WS_RATELIMIT
    secrets:
      - node_password
      - node_private_key
    entrypoint: /entrypoint.sh
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "200m"
        max-file: "10"

volumes:
  chaindata:

secrets:
  node_password:
    file: ./password.txt
  node_private_key:
    file: ./private_key.txt

networks:
  docker-compose_default:
    external: true